### ISSUE TITLE
Version difficulties with ruby-wasm

### ISSUE THREAD

**Issue by noahgibbs** [scarpe-team/scarpe-wasm#10]
It looks like ruby-wasm changed release filename conventions starting with 2.4.0. Which means wasify isn't working with newer releases. I've tried out a couple of possible fixes. The filename difference isn't too hard, but then when I do that, I get different problems. It looks like newer ruby.wasm releases can't deal with tempdir. It reports having no usable temp directory available.

Rolling back to version 2.3.0 doesn't seem to fix that problem, so maybe it's some other recent code change in Scarpe? 2.2.0 has that weird "initialize" problem for me right now because it can't deal with recent wasi-vfs versions.

Here's the JS log from the tmpdir error:

```
Uncaught (in promise) Error: /usr/local/lib/ruby/3.2.0/tmpdir.rb:38:in `tmpdir': could not find a temporary directory (ArgumentError)
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes/constants.rb:16:in `find_lib_dir'
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes/constants.rb:24:in `<module:Constants>'
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes/constants.rb:5:in `<class:Shoes>'
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes/constants.rb:4:in `<top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes.rb:19:in `require_relative'
/usr/local/lib/ruby/gems/3.2.0/gems/lacci-0.3.0/lib/shoes.rb:19:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/local/lib/ruby/gems/3.2.0/gems/scarpe-wasm-0.1.0/lib/scarpe/wasm_local.rb:6:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
eval:1:in `<main>'
    at checkStatusTag (browser.umd.js:1281:21)
    at browser.umd.js:1318:11
    at wrapRbOperation (browser.umd.js:1288:18)
    at evalRbCode (browser.umd.js:1316:14)
    at RubyVM.eval (browser.umd.js:1004:18)
    at main (index_button_alert.rb.html:14:8)
```

**Comment by noahgibbs** [comment]
At this point I'm not having any luck using any combination of ruby-wasm and wasi-vfs versions, even older ones. Not sure what changed. I can remove the tmpdir-based code from lacci/lib/shoes/constants.rb and we still get a memory access out of bounds. This is true even if I switch the browser.umd.js to the correct version.

For instance, this is with wasi-vfs 0.1.1 and ruby-wasm 2.3.0, so also browser.umd.js from 2.3.0:

```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at 0b41eb42:0xa1c755
    at 0b41eb42:0xa1c108
    at 0b41eb42:0x6cf919
    at 0b41eb42:0x55cb0
    at RbAbiGuest.rbVmBugreport (browser.umd.js:2244:53)
    at exports.<computed> [as rbVmBugreport] (browser.umd.js:2651:46)
    at wrapRbOperation (browser.umd.js:3134:20)
    at evalRbCode (browser.umd.js:3154:14)
    at RubyVM.eval (browser.umd.js:2888:18)
    at main (index_button_alert.rb.html:18:8)
$func12179 @ 0b41eb42:0xa1c755
$func12172 @ 0b41eb42:0xa1c108
$func7104 @ 0b41eb42:0x6cf919
$rb-vm-bugreport:_func___->___ @ 0b41eb42:0x55cb0
rbVmBugreport @ browser.umd.js:2244
exports.<computed> @ browser.umd.js:2651
wrapRbOperation @ browser.umd.js:3134
evalRbCode @ browser.umd.js:3154
eval @ browser.umd.js:2888
main @ index_button_alert.rb.html:18
await in main (async)
(anonymous) @ index_button_alert.rb.html:21
```

**Comment by noahgibbs** [comment]
Shoes-Spec started breaking on 15th December, presumably for this reason, and I started getting these console errors at basically the same time. I've tried rewinding Scarpe to before that. I'm pretty sure that the "latest" link we were using with curl to download ruby-wasm would only give us a numbered release, not a nightly. So presumably we were working with 2.2.0 and 2.3.0. We used wasi-vfs 0.1.1 for a very long time, then switched to 0.5.0 when ruby-wasm added support for it. Looks like 26 Nov was when I noticed and updated shoes-spec CI to use wasi-vfs 0.5.0.

**Comment by noahgibbs** [comment]
Looks like we're somehow hardcoding using the latest ruby-wasm. This broke when a new version came out and I couldn't use it. But even when setting browser.umd.js to not-latest and downloading an old release, everything breaks. Seems to be fine to use an older wasi-vfs, so that's not the problem. Something else is clearly hardcoding.

But using latest fixes this.
